/*
 * MainPanel.java
 *
 * Created on __DATE__, __TIME__
 */

package com.fengyun.atm.model.client.frame;
import java.awt.Dimension;
import java.awt.Rectangle;
import java.awt.BorderLayout;
import java.awt.ComponentOrientation;

/**
 *
 * @author  __USER__
 */
public class MainPanel extends javax.swing.JFrame
{

	/**
	 * 原来写这篇代码的时候，只有我和上帝知道它是干嘛的
	 * 现在只有上帝知道了
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/** Creates new form MainPanel */
	public MainPanel()
	{
		setMinimumSize(new Dimension(300, 400));
		getContentPane().setMinimumSize(new Dimension(300, 400));
		setSize(new Dimension(251, 449));
		setBounds(new Rectangle(0, 0, 300, 400));
		initComponents();
		setBounds(100, 100, 300, 400);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents()
	{

		jLabel1 = new javax.swing.JLabel();
		jPanel1 = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("BAM Client");
		setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		

		jLabel1.setFont(new java.awt.Font("微软雅黑", 1, 24));
		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel1.setText("ICBC ATM Terminal");
		getContentPane().add(jLabel1, BorderLayout.CENTER);

		jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER,
				20, 50));

		jButton1.setText("\u6ce8\u518c");
		jPanel1.add(jButton1);

		jButton2.setText("\u767b\u9646");
		jPanel1.add(jButton2);

		getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[])
	{
		java.awt.EventQueue.invokeLater(new Runnable()
		{
			public void run()
			{
				new MainPanel().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel1;
	// End of variables declaration//GEN-END:variables

}